### PR TITLE
fix: import "set-cookie-parser" as commonjs

### LINKED ISSUE #62: Can't import the named export 'splitCookiesString'
Hi There, Facing the below issue , while building the application. (npm run build)
Can't import the named export 'splitCookiesString' from non EcmaScript module (only default export is available)
Can you please check once

import {splitCookiesString}  from "set-cookie-parser";

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #62

### CODE REVIEW

**Comment by koddsson** [comment]
Hey! I tried to apply these changes to `index.mjs` in my `node_modules` but am now getting a error that there's no default export:

```
SyntaxError: The requested module '/__wds-outside-root__/2/koddsson/headers-polyfill/node_modules/set-cookie-parser/lib/set-cookie.js' does not provide an export named 'default'
```

I tried to remedy that by importing everything with a wildcard import:

```diff
diff --git a/src/Headers.ts b/src/Headers.ts
index 736630c..d6a46b8 100644
--- a/src/Headers.ts
+++ b/src/Headers.ts
@@ -1,4 +1,4 @@
-import setCookieParser from 'set-cookie-parser'
+import * as setCookieParser from 'set-cookie-parser'
 import { HeadersList, HeadersObject } from './glossary'
 import { normalizeHeaderName } from './utils/normalizeHeaderName'
 import { normalizeHeaderValue } from './utils/normalizeHeaderValue'
```

But then I get this new error:

```
ReferenceError: module is not defined
        at ../../koddsson/headers-polyfill/node_modules/set-cookie-parser/lib/set-cookie.js:223:1
```

I haven't used `tsup` before so I'm not sure what is the canonical way to handle this. I thought maybe a dynamic import would be good but it doesn't seem to work with a CJS output. Unless the import is put into the function where it's used but then the whole function needs to be marked `async` and the API would then be different.

**Comment by mattcosta7** [comment]
I wonder if we would be better off listing `set-cookie-parser` as a devDependency so it gets bundled into headers-polyfill, instead of relying on the external module?  this should alleviate potential esm issues?

**Comment by mattcosta7** [comment]
> I wonder if we would be better off listing `set-cookie-parser` as a devDependency so it gets bundled into headers-polyfill, instead of relying on the external module? this should alleviate potential esm issues?
> 
> since I don't believe set-cookie-parser has an esm output?

Added here - https://github.com/mswjs/headers-polyfill/pull/65

**Comment by kettanaito** [comment]
@mattcosta7, you're right, it's not an ESM. I forgot about the bundling strategy, it's still quite new to me. Let me take a look at your pull request, thanks for opening that!

**Comment by kettanaito** [comment]
Closed in favor of #63

**Pull request closed without merging**
