### PR TITLE
feat: remove ".all()", move ".raw()" to "getRawHeaders()"

### LINKED ISSUE #67: Move custom Headers methods to transformer functions
To improve specification-compliance, we must not set any custom methods on the `Headers` instance. This includes:

- `all()`
- `raw()`

Instead, remove those methods and implement them as transformers:

```js
import { Headers, getAllHeaders, getRawHeaders } from 'headers-polyfill'

const headers = new Headers({})
getAllHeaders(headers)
getRawHeaders(headers)
```

### PR DESCRIPTION
**Pull request by kettanaito**
BREAKING CHANGE

- Closes #67

### CODE REVIEW

**Comment by kettanaito** [comment]
## Released: v3.3.0 🎉

This has been released in v3.3.0!

- 📄 [**Release notes**](https://github.com/mswjs/headers-polyfill/releases/tag/v3.3.0)
- 📦 [npm package](https://www.npmjs.com/package/headers-polyfill/v/3.3.0)

Make sure to always update to the latest version (`npm i headers-polyfill@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by MichaelDeBoey** [comment]
@kettanaito This should have been released in v4.0.0 as this is a breaking change

**Comment by kettanaito** [comment]
@MichaelDeBoey, I know, my mistake. I've not included the breaking change comment in the commit's body correctly for it to trigger a major release. Would have to update the consumers, and meanwhile recommend pinning to '3.2.x'. A shame, truly.

**Comment by MichaelDeBoey** [comment]
You could always revert and do a (manual) patch release?

**Comment by kettanaito** [comment]
If I haven't gone and released the next major version afterward, I could do that. I'm on a streak today.

**Comment by smaspe** [comment]
given how that's the only "feature" of 3.3.0 you could also unpublish it?

**Comment by kettanaito** [comment]
@smaspe, unfortunately, there's no concept of unpublishing a package on NPM. Upgrade to the latest version, it's been released since my last comment. If it's a transitive dependency, pin it using your package manager.

**Pull request merged**
